version: '3.3'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      WORK_DIR: /usr/src/app
      PORT: 8080
    ports:
      - "4444:8080"